# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            nomadic programmer
tagline:          'helder da rocha'
description:      'thoughts, ideas and discoveries from technological journeys'
url:              http://helderdarocha.github.io

author:
  name:           'Helder da Rocha'
  url:            http://github.com/helderdarocha
  copyright:      2014

paginate:         5